name:  Dagger Build

on:
  push:
      branches-ignore:
      - 'master'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '11', '17' ]
        os: [ 'ubuntu-latest', 'windows-latest' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '8'
        architecture: x64
        targets: 'JDK8'
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: '${{ matrix.java }}'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package  -DjavaVersion=${{ matrix.java }} -Djdk8=${JDK8}
    - name: Test with Maven
      run: mvn -B test -DjavaVersion=${{ matrix.java }} -Djdk8=${JDK8}
