name:  Dagger Build

on:
  push:
      branches-ignore:
      - 'master'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '11' ]
        os: [ 'ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: '${{ matrix.distribution }}'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: '${{ matrix.java }}'
        distribution: '${{ matrix.distribution }}'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package  -Djava.version=${{ matrix.java }}
    - name: Test with Maven
      run: mvn -B test -Djava.version=${{ matrix.java }}
    #- name: Clean and Deploy with Maven
    #  run: mvn clean source:jar javadoc:jar deploy --settings=".buildscript/settings.xml" -Dmaven.test.skip=true -Dinvoker.skip=true
